[boms]
grpc = { module = "io.grpc:grpc-bom", version = "1.50.0" }

[versions]
protoc = "3.21.7"
protobuf-gradle-plguin = "0.9.1"
grpc-kotlin = "1.3.0"

[libraries.protobuf-gradle-plugin]
module = "com.google.protobuf:protobuf-gradle-plugin"
version.ref = "protobuf-gradle-plguin"

[libraries.protobuf-java]
module = "com.google.protobuf:protobuf-java"
version.ref = "protoc"
[libraries.protoc]
module = "com.google.protobuf:protoc"
version.ref = "protoc"

[libraries.grpc-kotlin-protoc]
module = "io.grpc:protoc-gen-grpc-kotlin"
version.ref = "grpc-kotlin"
[libraries.grpc-kotlin-stub]
module = "io.grpc:grpc-kotlin-stub"
version.ref = "grpc-kotlin"
[libraries.grpc-protobuf]
module = "io.grpc:grpc-protobuf"
